-- MySaaS Premium Supabase Database Schema Migration
-- Run this in your Supabase Dashboard SQL Editor (https://database.new)

-- =========================================================================
-- ⚡ 1. SCHEMA UPGRADES (Safe, non-destructive alterations)
-- =========================================================================

-- Ensure Profiles Table has all required premium fields
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS api_key TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS fake_door_waitlisted BOOLEAN DEFAULT FALSE;

-- Ensure Profiles Table has all Creem.io premium billing fields
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_id TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS customer_id TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'none';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS current_period_start TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS current_period_end TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS cancel_at_period_end BOOLEAN DEFAULT FALSE;

-- Ensure tier is present and set the default constraint check
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'free';
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_tier_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_tier_check CHECK (tier IN ('free', 'pro', 'admin', 'api'));

-- =========================================================================
-- 💾 2. CREATE AUXILIARY TABLES (If they do not exist)
-- =========================================================================

-- Usage Logs Table (Metered API/Document compilations)
CREATE TABLE IF NOT EXISTS public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  ip_hash text not null,
  tool_id text not null,
  tier integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Saved History Table (Pro history caching)
CREATE TABLE IF NOT EXISTS public.saved_history (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  tool_id text not null,
  file_name text not null,
  content_preview text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fake Checkout Clicks Table (Monetization interest metrics)
CREATE TABLE IF NOT EXISTS public.fake_checkout_clicks (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  plan_clicked text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =========================================================================
-- ⚡ 3. PERFORMANCE INDEXING
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_usage_created_at ON public.usage_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_usage_user_id ON public.usage_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_usage_ip_hash ON public.usage_logs(ip_hash);
CREATE INDEX IF NOT EXISTS idx_history_user_id ON public.saved_history(user_id);

-- =========================================================================
-- 🔐 4. SECURITY & ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

-- Enable RLS across all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fake_checkout_clicks ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Allow public read access to profiles" ON public.profiles;
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow users to insert their own profile" ON public.profiles;
CREATE POLICY "Allow users to insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Usage Logs Policies
DROP POLICY IF EXISTS "Allow insert access for all" ON public.usage_logs;
CREATE POLICY "Allow insert access for all" ON public.usage_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow users to read their own usage logs" ON public.usage_logs;
CREATE POLICY "Allow users to read their own usage logs" ON public.usage_logs FOR SELECT USING (auth.uid() = user_id);

-- Saved History Policies
DROP POLICY IF EXISTS "Allow users to manage their own history" ON public.saved_history;
CREATE POLICY "Allow users to manage their own history" ON public.saved_history FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Fake Checkout Clicks Policies
DROP POLICY IF EXISTS "Allow insert access for checkout metrics" ON public.fake_checkout_clicks;
CREATE POLICY "Allow insert access for checkout metrics" ON public.fake_checkout_clicks FOR INSERT WITH CHECK (true);

-- =========================================================================
-- ⚡ 5. BACKEND DATABASE SIGNUP TRIGGERS (Zero-Migration Auto-Sync)
-- =========================================================================

-- Create or update the handle_new_user trigger function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- Insert base profile row into profiles table
  INSERT INTO public.profiles (id, email, name, username, tier)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    'free'
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email;

  -- Seed premium sample documents in history to show a beautiful initial workspace state!
  INSERT INTO public.saved_history (user_id, tool_id, file_name, content_preview)
  VALUES 
    (new.id, 'json', 'acme_q1_financials_beautified.json', '{"status":"success","data":{"revenue":145200,"growth_pct":12.4},"message":"Formatted using MySaaS JSON repair engine"}'),
    (new.id, 'universal-ai-formatter', 'onboarding_email_template_premium.txt', 'Welcome to the console! This document was formatted using the Universal AI Formatter tool.')
  ON CONFLICT DO NOTHING;
    
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function every time a user is created in auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
